### ISSUE TITLE
Missing v prefix in 1.5.2 release

### ISSUE THREAD

**Issue by lath** [mouuff/go-rocket-update#19]
Hello, thanks a ton for making this tool!

Was about to experiment a bit with it but noticed that the most recent release is missing the v-prefix in its tag, causing version handlers to not approve of it. I assume this was a mistake seeing how all previous tags are prefixed accordingly.

**Comment by mouuff** [comment]
Thanks a lot for reporting that, and for your interest in this project!
It was a mistake indeed, this issue has been resolved! 👍
